//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace DataProject.Domain
{
    #region Bağlamlar
    
    /// <summary>
    /// Kullanılabilir Meta Veri Belgeleri yok.
    /// </summary>
    public partial class LogoDataModel : ObjectContext
    {
        #region Oluşturucular
    
        /// <summary>
        /// Yeni LogoDataModel nesnesini, uygulama yapılandırma dosyasının 'LogoDataModel' bölümünde bulunan bağlantı dizesini kullanarak başlatır.
        /// </summary>
        public LogoDataModel() : base("name=LogoDataModel", "LogoDataModel")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        /// <summary>
        /// Yeni bir LogoDataModel nesnesi başlatın.
        /// </summary>
        public LogoDataModel(string connectionString) : base(connectionString, "LogoDataModel")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        /// <summary>
        /// Yeni bir LogoDataModel nesnesi başlatın.
        /// </summary>
        public LogoDataModel(EntityConnection connection) : base(connection, "LogoDataModel")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        #endregion
    
        #region Kısmi Metotlar
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Özellikleri
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        public ObjectSet<TBL_BI_REPORT_IK_SICIL> TBL_BI_REPORT_IK_SICIL
        {
            get
            {
                if ((_TBL_BI_REPORT_IK_SICIL == null))
                {
                    _TBL_BI_REPORT_IK_SICIL = base.CreateObjectSet<TBL_BI_REPORT_IK_SICIL>("TBL_BI_REPORT_IK_SICIL");
                }
                return _TBL_BI_REPORT_IK_SICIL;
            }
        }
        private ObjectSet<TBL_BI_REPORT_IK_SICIL> _TBL_BI_REPORT_IK_SICIL;
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        public ObjectSet<TBL_BI_REPORT_IK_SICIL_OLD> TBL_BI_REPORT_IK_SICIL_OLD
        {
            get
            {
                if ((_TBL_BI_REPORT_IK_SICIL_OLD == null))
                {
                    _TBL_BI_REPORT_IK_SICIL_OLD = base.CreateObjectSet<TBL_BI_REPORT_IK_SICIL_OLD>("TBL_BI_REPORT_IK_SICIL_OLD");
                }
                return _TBL_BI_REPORT_IK_SICIL_OLD;
            }
        }
        private ObjectSet<TBL_BI_REPORT_IK_SICIL_OLD> _TBL_BI_REPORT_IK_SICIL_OLD;

        #endregion

        #region AddTo Metotları
    
        /// <summary>
        /// TBL_BI_REPORT_IK_SICIL EntitySet'e yeni nesne ekleme için Deprecated Metodu. Bunun yerine, ilişkili ObjectSet&lt;T&gt; özelliğinin .Add metodunu kullanmayı deneyin.
        /// </summary>
        public void AddToTBL_BI_REPORT_IK_SICIL(TBL_BI_REPORT_IK_SICIL tBL_BI_REPORT_IK_SICIL)
        {
            base.AddObject("TBL_BI_REPORT_IK_SICIL", tBL_BI_REPORT_IK_SICIL);
        }
    
        /// <summary>
        /// TBL_BI_REPORT_IK_SICIL_OLD EntitySet'e yeni nesne ekleme için Deprecated Metodu. Bunun yerine, ilişkili ObjectSet&lt;T&gt; özelliğinin .Add metodunu kullanmayı deneyin.
        /// </summary>
        public void AddToTBL_BI_REPORT_IK_SICIL_OLD(TBL_BI_REPORT_IK_SICIL_OLD tBL_BI_REPORT_IK_SICIL_OLD)
        {
            base.AddObject("TBL_BI_REPORT_IK_SICIL_OLD", tBL_BI_REPORT_IK_SICIL_OLD);
        }

        #endregion

    }

    #endregion

    #region Varlıklar
    
    /// <summary>
    /// Kullanılabilir Meta Veri Belgeleri yok.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LogoModel", Name="TBL_BI_REPORT_IK_SICIL")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBL_BI_REPORT_IK_SICIL : EntityObject
    {
        #region Factory Metodu
    
        /// <summary>
        /// Yeni bir TBL_BI_REPORT_IK_SICIL nesnesi oluşturun.
        /// </summary>
        /// <param name="cinsiyet">Cinsiyet özelliğinin ilk değeri.</param>
        /// <param name="dOĞUM_TARİHİ">DOĞUM_TARİHİ özelliğinin ilk değeri.</param>
        public static TBL_BI_REPORT_IK_SICIL CreateTBL_BI_REPORT_IK_SICIL(global::System.String cinsiyet, global::System.DateTime dOĞUM_TARİHİ)
        {
            TBL_BI_REPORT_IK_SICIL tBL_BI_REPORT_IK_SICIL = new TBL_BI_REPORT_IK_SICIL();
            tBL_BI_REPORT_IK_SICIL.Cinsiyet = cinsiyet;
            tBL_BI_REPORT_IK_SICIL.DOĞUM_TARİHİ = dOĞUM_TARİHİ;
            return tBL_BI_REPORT_IK_SICIL;
        }

        #endregion

        #region Basit Özellikler
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SicilNo
        {
            get
            {
                return _SicilNo;
            }
            set
            {
                OnSicilNoChanging(value);
                ReportPropertyChanging("SicilNo");
                _SicilNo = StructuralObject.SetValidValue(value, true, "SicilNo");
                ReportPropertyChanged("SicilNo");
                OnSicilNoChanged();
            }
        }
        private global::System.String _SicilNo;
        partial void OnSicilNoChanging(global::System.String value);
        partial void OnSicilNoChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ad
        {
            get
            {
                return _Ad;
            }
            set
            {
                OnAdChanging(value);
                ReportPropertyChanging("Ad");
                _Ad = StructuralObject.SetValidValue(value, true, "Ad");
                ReportPropertyChanged("Ad");
                OnAdChanged();
            }
        }
        private global::System.String _Ad;
        partial void OnAdChanging(global::System.String value);
        partial void OnAdChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Soyad
        {
            get
            {
                return _Soyad;
            }
            set
            {
                OnSoyadChanging(value);
                ReportPropertyChanging("Soyad");
                _Soyad = StructuralObject.SetValidValue(value, true, "Soyad");
                ReportPropertyChanged("Soyad");
                OnSoyadChanged();
            }
        }
        private global::System.String _Soyad;
        partial void OnSoyadChanging(global::System.String value);
        partial void OnSoyadChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> KurumKodu
        {
            get
            {
                return _KurumKodu;
            }
            set
            {
                OnKurumKoduChanging(value);
                ReportPropertyChanging("KurumKodu");
                _KurumKodu = StructuralObject.SetValidValue(value, "KurumKodu");
                ReportPropertyChanged("KurumKodu");
                OnKurumKoduChanged();
            }
        }
        private Nullable<global::System.Int16> _KurumKodu;
        partial void OnKurumKoduChanging(Nullable<global::System.Int16> value);
        partial void OnKurumKoduChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KurumAdi
        {
            get
            {
                return _KurumAdi;
            }
            set
            {
                OnKurumAdiChanging(value);
                ReportPropertyChanging("KurumAdi");
                _KurumAdi = StructuralObject.SetValidValue(value, true, "KurumAdi");
                ReportPropertyChanged("KurumAdi");
                OnKurumAdiChanged();
            }
        }
        private global::System.String _KurumAdi;
        partial void OnKurumAdiChanging(global::System.String value);
        partial void OnKurumAdiChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> IsYeriKodu
        {
            get
            {
                return _IsYeriKodu;
            }
            set
            {
                OnIsYeriKoduChanging(value);
                ReportPropertyChanging("IsYeriKodu");
                _IsYeriKodu = StructuralObject.SetValidValue(value, "IsYeriKodu");
                ReportPropertyChanged("IsYeriKodu");
                OnIsYeriKoduChanged();
            }
        }
        private Nullable<global::System.Int16> _IsYeriKodu;
        partial void OnIsYeriKoduChanging(Nullable<global::System.Int16> value);
        partial void OnIsYeriKoduChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IsYeriAdi
        {
            get
            {
                return _IsYeriAdi;
            }
            set
            {
                OnIsYeriAdiChanging(value);
                ReportPropertyChanging("IsYeriAdi");
                _IsYeriAdi = StructuralObject.SetValidValue(value, true, "IsYeriAdi");
                ReportPropertyChanged("IsYeriAdi");
                OnIsYeriAdiChanged();
            }
        }
        private global::System.String _IsYeriAdi;
        partial void OnIsYeriAdiChanging(global::System.String value);
        partial void OnIsYeriAdiChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> BolumKodu
        {
            get
            {
                return _BolumKodu;
            }
            set
            {
                OnBolumKoduChanging(value);
                ReportPropertyChanging("BolumKodu");
                _BolumKodu = StructuralObject.SetValidValue(value, "BolumKodu");
                ReportPropertyChanged("BolumKodu");
                OnBolumKoduChanged();
            }
        }
        private Nullable<global::System.Int16> _BolumKodu;
        partial void OnBolumKoduChanging(Nullable<global::System.Int16> value);
        partial void OnBolumKoduChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BolumAdi
        {
            get
            {
                return _BolumAdi;
            }
            set
            {
                OnBolumAdiChanging(value);
                ReportPropertyChanging("BolumAdi");
                _BolumAdi = StructuralObject.SetValidValue(value, true, "BolumAdi");
                ReportPropertyChanged("BolumAdi");
                OnBolumAdiChanged();
            }
        }
        private global::System.String _BolumAdi;
        partial void OnBolumAdiChanging(global::System.String value);
        partial void OnBolumAdiChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AltBolumKodu
        {
            get
            {
                return _AltBolumKodu;
            }
            set
            {
                OnAltBolumKoduChanging(value);
                ReportPropertyChanging("AltBolumKodu");
                _AltBolumKodu = StructuralObject.SetValidValue(value, true, "AltBolumKodu");
                ReportPropertyChanged("AltBolumKodu");
                OnAltBolumKoduChanged();
            }
        }
        private global::System.String _AltBolumKodu;
        partial void OnAltBolumKoduChanging(global::System.String value);
        partial void OnAltBolumKoduChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AltBolumAdi
        {
            get
            {
                return _AltBolumAdi;
            }
            set
            {
                OnAltBolumAdiChanging(value);
                ReportPropertyChanging("AltBolumAdi");
                _AltBolumAdi = StructuralObject.SetValidValue(value, true, "AltBolumAdi");
                ReportPropertyChanged("AltBolumAdi");
                OnAltBolumAdiChanged();
            }
        }
        private global::System.String _AltBolumAdi;
        partial void OnAltBolumAdiChanging(global::System.String value);
        partial void OnAltBolumAdiChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> BirimKodu
        {
            get
            {
                return _BirimKodu;
            }
            set
            {
                OnBirimKoduChanging(value);
                ReportPropertyChanging("BirimKodu");
                _BirimKodu = StructuralObject.SetValidValue(value, "BirimKodu");
                ReportPropertyChanged("BirimKodu");
                OnBirimKoduChanged();
            }
        }
        private Nullable<global::System.Int16> _BirimKodu;
        partial void OnBirimKoduChanging(Nullable<global::System.Int16> value);
        partial void OnBirimKoduChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BirimAdi
        {
            get
            {
                return _BirimAdi;
            }
            set
            {
                OnBirimAdiChanging(value);
                ReportPropertyChanging("BirimAdi");
                _BirimAdi = StructuralObject.SetValidValue(value, true, "BirimAdi");
                ReportPropertyChanged("BirimAdi");
                OnBirimAdiChanged();
            }
        }
        private global::System.String _BirimAdi;
        partial void OnBirimAdiChanging(global::System.String value);
        partial void OnBirimAdiChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PozisyonKodu
        {
            get
            {
                return _PozisyonKodu;
            }
            set
            {
                OnPozisyonKoduChanging(value);
                ReportPropertyChanging("PozisyonKodu");
                _PozisyonKodu = StructuralObject.SetValidValue(value, true, "PozisyonKodu");
                ReportPropertyChanged("PozisyonKodu");
                OnPozisyonKoduChanged();
            }
        }
        private global::System.String _PozisyonKodu;
        partial void OnPozisyonKoduChanging(global::System.String value);
        partial void OnPozisyonKoduChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PozisyonAdı
        {
            get
            {
                return _PozisyonAdı;
            }
            set
            {
                OnPozisyonAdıChanging(value);
                ReportPropertyChanging("PozisyonAdı");
                _PozisyonAdı = StructuralObject.SetValidValue(value, true, "PozisyonAdı");
                ReportPropertyChanged("PozisyonAdı");
                OnPozisyonAdıChanged();
            }
        }
        private global::System.String _PozisyonAdı;
        partial void OnPozisyonAdıChanging(global::System.String value);
        partial void OnPozisyonAdıChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cinsiyet
        {
            get
            {
                return _Cinsiyet;
            }
            set
            {
                if (_Cinsiyet != value)
                {
                    OnCinsiyetChanging(value);
                    ReportPropertyChanging("Cinsiyet");
                    _Cinsiyet = StructuralObject.SetValidValue(value, false, "Cinsiyet");
                    ReportPropertyChanged("Cinsiyet");
                    OnCinsiyetChanged();
                }
            }
        }
        private global::System.String _Cinsiyet;
        partial void OnCinsiyetChanging(global::System.String value);
        partial void OnCinsiyetChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DereceKodu
        {
            get
            {
                return _DereceKodu;
            }
            set
            {
                OnDereceKoduChanging(value);
                ReportPropertyChanging("DereceKodu");
                _DereceKodu = StructuralObject.SetValidValue(value, true, "DereceKodu");
                ReportPropertyChanged("DereceKodu");
                OnDereceKoduChanged();
            }
        }
        private global::System.String _DereceKodu;
        partial void OnDereceKoduChanging(global::System.String value);
        partial void OnDereceKoduChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DereceAdi
        {
            get
            {
                return _DereceAdi;
            }
            set
            {
                OnDereceAdiChanging(value);
                ReportPropertyChanging("DereceAdi");
                _DereceAdi = StructuralObject.SetValidValue(value, true, "DereceAdi");
                ReportPropertyChanged("DereceAdi");
                OnDereceAdiChanged();
            }
        }
        private global::System.String _DereceAdi;
        partial void OnDereceAdiChanging(global::System.String value);
        partial void OnDereceAdiChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BordroKodu
        {
            get
            {
                return _BordroKodu;
            }
            set
            {
                OnBordroKoduChanging(value);
                ReportPropertyChanging("BordroKodu");
                _BordroKodu = StructuralObject.SetValidValue(value, true, "BordroKodu");
                ReportPropertyChanged("BordroKodu");
                OnBordroKoduChanged();
            }
        }
        private global::System.String _BordroKodu;
        partial void OnBordroKoduChanging(global::System.String value);
        partial void OnBordroKoduChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IseGirisTarihi
        {
            get
            {
                return _IseGirisTarihi;
            }
            set
            {
                OnIseGirisTarihiChanging(value);
                ReportPropertyChanging("IseGirisTarihi");
                _IseGirisTarihi = StructuralObject.SetValidValue(value, true, "IseGirisTarihi");
                ReportPropertyChanged("IseGirisTarihi");
                OnIseGirisTarihiChanged();
            }
        }
        private global::System.String _IseGirisTarihi;
        partial void OnIseGirisTarihiChanging(global::System.String value);
        partial void OnIseGirisTarihiChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IstenCikisTarihi
        {
            get
            {
                return _IstenCikisTarihi;
            }
            set
            {
                OnIstenCikisTarihiChanging(value);
                ReportPropertyChanging("IstenCikisTarihi");
                _IstenCikisTarihi = StructuralObject.SetValidValue(value, true, "IstenCikisTarihi");
                ReportPropertyChanged("IstenCikisTarihi");
                OnIstenCikisTarihiChanged();
            }
        }
        private global::System.String _IstenCikisTarihi;
        partial void OnIstenCikisTarihiChanging(global::System.String value);
        partial void OnIstenCikisTarihiChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> KidemYil
        {
            get
            {
                return _KidemYil;
            }
            set
            {
                OnKidemYilChanging(value);
                ReportPropertyChanging("KidemYil");
                _KidemYil = StructuralObject.SetValidValue(value, "KidemYil");
                ReportPropertyChanged("KidemYil");
                OnKidemYilChanged();
            }
        }
        private Nullable<global::System.Int32> _KidemYil;
        partial void OnKidemYilChanging(Nullable<global::System.Int32> value);
        partial void OnKidemYilChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BirincilYoneticiSicilNo
        {
            get
            {
                return _BirincilYoneticiSicilNo;
            }
            set
            {
                OnBirincilYoneticiSicilNoChanging(value);
                ReportPropertyChanging("BirincilYoneticiSicilNo");
                _BirincilYoneticiSicilNo = StructuralObject.SetValidValue(value, true, "BirincilYoneticiSicilNo");
                ReportPropertyChanged("BirincilYoneticiSicilNo");
                OnBirincilYoneticiSicilNoChanged();
            }
        }
        private global::System.String _BirincilYoneticiSicilNo;
        partial void OnBirincilYoneticiSicilNoChanging(global::System.String value);
        partial void OnBirincilYoneticiSicilNoChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BirincilYoneticiAd
        {
            get
            {
                return _BirincilYoneticiAd;
            }
            set
            {
                OnBirincilYoneticiAdChanging(value);
                ReportPropertyChanging("BirincilYoneticiAd");
                _BirincilYoneticiAd = StructuralObject.SetValidValue(value, true, "BirincilYoneticiAd");
                ReportPropertyChanged("BirincilYoneticiAd");
                OnBirincilYoneticiAdChanged();
            }
        }
        private global::System.String _BirincilYoneticiAd;
        partial void OnBirincilYoneticiAdChanging(global::System.String value);
        partial void OnBirincilYoneticiAdChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BirincilYoneticiSoyad
        {
            get
            {
                return _BirincilYoneticiSoyad;
            }
            set
            {
                OnBirincilYoneticiSoyadChanging(value);
                ReportPropertyChanging("BirincilYoneticiSoyad");
                _BirincilYoneticiSoyad = StructuralObject.SetValidValue(value, true, "BirincilYoneticiSoyad");
                ReportPropertyChanged("BirincilYoneticiSoyad");
                OnBirincilYoneticiSoyadChanged();
            }
        }
        private global::System.String _BirincilYoneticiSoyad;
        partial void OnBirincilYoneticiSoyadChanging(global::System.String value);
        partial void OnBirincilYoneticiSoyadChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BirincilYoneticiUnvanKodu
        {
            get
            {
                return _BirincilYoneticiUnvanKodu;
            }
            set
            {
                OnBirincilYoneticiUnvanKoduChanging(value);
                ReportPropertyChanging("BirincilYoneticiUnvanKodu");
                _BirincilYoneticiUnvanKodu = StructuralObject.SetValidValue(value, true, "BirincilYoneticiUnvanKodu");
                ReportPropertyChanged("BirincilYoneticiUnvanKodu");
                OnBirincilYoneticiUnvanKoduChanged();
            }
        }
        private global::System.String _BirincilYoneticiUnvanKodu;
        partial void OnBirincilYoneticiUnvanKoduChanging(global::System.String value);
        partial void OnBirincilYoneticiUnvanKoduChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IkincilYoneticiSicilNo
        {
            get
            {
                return _IkincilYoneticiSicilNo;
            }
            set
            {
                OnIkincilYoneticiSicilNoChanging(value);
                ReportPropertyChanging("IkincilYoneticiSicilNo");
                _IkincilYoneticiSicilNo = StructuralObject.SetValidValue(value, true, "IkincilYoneticiSicilNo");
                ReportPropertyChanged("IkincilYoneticiSicilNo");
                OnIkincilYoneticiSicilNoChanged();
            }
        }
        private global::System.String _IkincilYoneticiSicilNo;
        partial void OnIkincilYoneticiSicilNoChanging(global::System.String value);
        partial void OnIkincilYoneticiSicilNoChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IkincilYoneticiAd
        {
            get
            {
                return _IkincilYoneticiAd;
            }
            set
            {
                OnIkincilYoneticiAdChanging(value);
                ReportPropertyChanging("IkincilYoneticiAd");
                _IkincilYoneticiAd = StructuralObject.SetValidValue(value, true, "IkincilYoneticiAd");
                ReportPropertyChanged("IkincilYoneticiAd");
                OnIkincilYoneticiAdChanged();
            }
        }
        private global::System.String _IkincilYoneticiAd;
        partial void OnIkincilYoneticiAdChanging(global::System.String value);
        partial void OnIkincilYoneticiAdChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IkincilYoneticiSoyad
        {
            get
            {
                return _IkincilYoneticiSoyad;
            }
            set
            {
                OnIkincilYoneticiSoyadChanging(value);
                ReportPropertyChanging("IkincilYoneticiSoyad");
                _IkincilYoneticiSoyad = StructuralObject.SetValidValue(value, true, "IkincilYoneticiSoyad");
                ReportPropertyChanged("IkincilYoneticiSoyad");
                OnIkincilYoneticiSoyadChanged();
            }
        }
        private global::System.String _IkincilYoneticiSoyad;
        partial void OnIkincilYoneticiSoyadChanging(global::System.String value);
        partial void OnIkincilYoneticiSoyadChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IkincilYoneticiUnvanKodu
        {
            get
            {
                return _IkincilYoneticiUnvanKodu;
            }
            set
            {
                OnIkincilYoneticiUnvanKoduChanging(value);
                ReportPropertyChanging("IkincilYoneticiUnvanKodu");
                _IkincilYoneticiUnvanKodu = StructuralObject.SetValidValue(value, true, "IkincilYoneticiUnvanKodu");
                ReportPropertyChanged("IkincilYoneticiUnvanKodu");
                OnIkincilYoneticiUnvanKoduChanged();
            }
        }
        private global::System.String _IkincilYoneticiUnvanKodu;
        partial void OnIkincilYoneticiUnvanKoduChanging(global::System.String value);
        partial void OnIkincilYoneticiUnvanKoduChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DOĞUM_TARİHİ
        {
            get
            {
                return _DOĞUM_TARİHİ;
            }
            set
            {
                if (_DOĞUM_TARİHİ != value)
                {
                    OnDOĞUM_TARİHİChanging(value);
                    ReportPropertyChanging("DOĞUM_TARİHİ");
                    _DOĞUM_TARİHİ = StructuralObject.SetValidValue(value, "DOĞUM_TARİHİ");
                    ReportPropertyChanged("DOĞUM_TARİHİ");
                    OnDOĞUM_TARİHİChanged();
                }
            }
        }
        private global::System.DateTime _DOĞUM_TARİHİ;
        partial void OnDOĞUM_TARİHİChanging(global::System.DateTime value);
        partial void OnDOĞUM_TARİHİChanged();

        #endregion

    }
    
    /// <summary>
    /// Kullanılabilir Meta Veri Belgeleri yok.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LogoModel", Name="TBL_BI_REPORT_IK_SICIL_OLD")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBL_BI_REPORT_IK_SICIL_OLD : EntityObject
    {
        #region Factory Metodu
    
        /// <summary>
        /// Yeni bir TBL_BI_REPORT_IK_SICIL_OLD nesnesi oluşturun.
        /// </summary>
        /// <param name="cinsiyet">Cinsiyet özelliğinin ilk değeri.</param>
        /// <param name="dOĞUM_TARİHİ">DOĞUM_TARİHİ özelliğinin ilk değeri.</param>
        public static TBL_BI_REPORT_IK_SICIL_OLD CreateTBL_BI_REPORT_IK_SICIL_OLD(global::System.String cinsiyet, global::System.DateTime dOĞUM_TARİHİ)
        {
            TBL_BI_REPORT_IK_SICIL_OLD tBL_BI_REPORT_IK_SICIL_OLD = new TBL_BI_REPORT_IK_SICIL_OLD();
            tBL_BI_REPORT_IK_SICIL_OLD.Cinsiyet = cinsiyet;
            tBL_BI_REPORT_IK_SICIL_OLD.DOĞUM_TARİHİ = dOĞUM_TARİHİ;
            return tBL_BI_REPORT_IK_SICIL_OLD;
        }

        #endregion

        #region Basit Özellikler
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SicilNo
        {
            get
            {
                return _SicilNo;
            }
            set
            {
                OnSicilNoChanging(value);
                ReportPropertyChanging("SicilNo");
                _SicilNo = StructuralObject.SetValidValue(value, true, "SicilNo");
                ReportPropertyChanged("SicilNo");
                OnSicilNoChanged();
            }
        }
        private global::System.String _SicilNo;
        partial void OnSicilNoChanging(global::System.String value);
        partial void OnSicilNoChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ad
        {
            get
            {
                return _Ad;
            }
            set
            {
                OnAdChanging(value);
                ReportPropertyChanging("Ad");
                _Ad = StructuralObject.SetValidValue(value, true, "Ad");
                ReportPropertyChanged("Ad");
                OnAdChanged();
            }
        }
        private global::System.String _Ad;
        partial void OnAdChanging(global::System.String value);
        partial void OnAdChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Soyad
        {
            get
            {
                return _Soyad;
            }
            set
            {
                OnSoyadChanging(value);
                ReportPropertyChanging("Soyad");
                _Soyad = StructuralObject.SetValidValue(value, true, "Soyad");
                ReportPropertyChanged("Soyad");
                OnSoyadChanged();
            }
        }
        private global::System.String _Soyad;
        partial void OnSoyadChanging(global::System.String value);
        partial void OnSoyadChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> KurumKodu
        {
            get
            {
                return _KurumKodu;
            }
            set
            {
                OnKurumKoduChanging(value);
                ReportPropertyChanging("KurumKodu");
                _KurumKodu = StructuralObject.SetValidValue(value, "KurumKodu");
                ReportPropertyChanged("KurumKodu");
                OnKurumKoduChanged();
            }
        }
        private Nullable<global::System.Int16> _KurumKodu;
        partial void OnKurumKoduChanging(Nullable<global::System.Int16> value);
        partial void OnKurumKoduChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KurumAdi
        {
            get
            {
                return _KurumAdi;
            }
            set
            {
                OnKurumAdiChanging(value);
                ReportPropertyChanging("KurumAdi");
                _KurumAdi = StructuralObject.SetValidValue(value, true, "KurumAdi");
                ReportPropertyChanged("KurumAdi");
                OnKurumAdiChanged();
            }
        }
        private global::System.String _KurumAdi;
        partial void OnKurumAdiChanging(global::System.String value);
        partial void OnKurumAdiChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> IsYeriKodu
        {
            get
            {
                return _IsYeriKodu;
            }
            set
            {
                OnIsYeriKoduChanging(value);
                ReportPropertyChanging("IsYeriKodu");
                _IsYeriKodu = StructuralObject.SetValidValue(value, "IsYeriKodu");
                ReportPropertyChanged("IsYeriKodu");
                OnIsYeriKoduChanged();
            }
        }
        private Nullable<global::System.Int16> _IsYeriKodu;
        partial void OnIsYeriKoduChanging(Nullable<global::System.Int16> value);
        partial void OnIsYeriKoduChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IsYeriAdi
        {
            get
            {
                return _IsYeriAdi;
            }
            set
            {
                OnIsYeriAdiChanging(value);
                ReportPropertyChanging("IsYeriAdi");
                _IsYeriAdi = StructuralObject.SetValidValue(value, true, "IsYeriAdi");
                ReportPropertyChanged("IsYeriAdi");
                OnIsYeriAdiChanged();
            }
        }
        private global::System.String _IsYeriAdi;
        partial void OnIsYeriAdiChanging(global::System.String value);
        partial void OnIsYeriAdiChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> BolumKodu
        {
            get
            {
                return _BolumKodu;
            }
            set
            {
                OnBolumKoduChanging(value);
                ReportPropertyChanging("BolumKodu");
                _BolumKodu = StructuralObject.SetValidValue(value, "BolumKodu");
                ReportPropertyChanged("BolumKodu");
                OnBolumKoduChanged();
            }
        }
        private Nullable<global::System.Int16> _BolumKodu;
        partial void OnBolumKoduChanging(Nullable<global::System.Int16> value);
        partial void OnBolumKoduChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BolumAdi
        {
            get
            {
                return _BolumAdi;
            }
            set
            {
                OnBolumAdiChanging(value);
                ReportPropertyChanging("BolumAdi");
                _BolumAdi = StructuralObject.SetValidValue(value, true, "BolumAdi");
                ReportPropertyChanged("BolumAdi");
                OnBolumAdiChanged();
            }
        }
        private global::System.String _BolumAdi;
        partial void OnBolumAdiChanging(global::System.String value);
        partial void OnBolumAdiChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AltBolumKodu
        {
            get
            {
                return _AltBolumKodu;
            }
            set
            {
                OnAltBolumKoduChanging(value);
                ReportPropertyChanging("AltBolumKodu");
                _AltBolumKodu = StructuralObject.SetValidValue(value, true, "AltBolumKodu");
                ReportPropertyChanged("AltBolumKodu");
                OnAltBolumKoduChanged();
            }
        }
        private global::System.String _AltBolumKodu;
        partial void OnAltBolumKoduChanging(global::System.String value);
        partial void OnAltBolumKoduChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AltBolumAdi
        {
            get
            {
                return _AltBolumAdi;
            }
            set
            {
                OnAltBolumAdiChanging(value);
                ReportPropertyChanging("AltBolumAdi");
                _AltBolumAdi = StructuralObject.SetValidValue(value, true, "AltBolumAdi");
                ReportPropertyChanged("AltBolumAdi");
                OnAltBolumAdiChanged();
            }
        }
        private global::System.String _AltBolumAdi;
        partial void OnAltBolumAdiChanging(global::System.String value);
        partial void OnAltBolumAdiChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> BirimKodu
        {
            get
            {
                return _BirimKodu;
            }
            set
            {
                OnBirimKoduChanging(value);
                ReportPropertyChanging("BirimKodu");
                _BirimKodu = StructuralObject.SetValidValue(value, "BirimKodu");
                ReportPropertyChanged("BirimKodu");
                OnBirimKoduChanged();
            }
        }
        private Nullable<global::System.Int16> _BirimKodu;
        partial void OnBirimKoduChanging(Nullable<global::System.Int16> value);
        partial void OnBirimKoduChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BirimAdi
        {
            get
            {
                return _BirimAdi;
            }
            set
            {
                OnBirimAdiChanging(value);
                ReportPropertyChanging("BirimAdi");
                _BirimAdi = StructuralObject.SetValidValue(value, true, "BirimAdi");
                ReportPropertyChanged("BirimAdi");
                OnBirimAdiChanged();
            }
        }
        private global::System.String _BirimAdi;
        partial void OnBirimAdiChanging(global::System.String value);
        partial void OnBirimAdiChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PozisyonKodu
        {
            get
            {
                return _PozisyonKodu;
            }
            set
            {
                OnPozisyonKoduChanging(value);
                ReportPropertyChanging("PozisyonKodu");
                _PozisyonKodu = StructuralObject.SetValidValue(value, true, "PozisyonKodu");
                ReportPropertyChanged("PozisyonKodu");
                OnPozisyonKoduChanged();
            }
        }
        private global::System.String _PozisyonKodu;
        partial void OnPozisyonKoduChanging(global::System.String value);
        partial void OnPozisyonKoduChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PozisyonAdı
        {
            get
            {
                return _PozisyonAdı;
            }
            set
            {
                OnPozisyonAdıChanging(value);
                ReportPropertyChanging("PozisyonAdı");
                _PozisyonAdı = StructuralObject.SetValidValue(value, true, "PozisyonAdı");
                ReportPropertyChanged("PozisyonAdı");
                OnPozisyonAdıChanged();
            }
        }
        private global::System.String _PozisyonAdı;
        partial void OnPozisyonAdıChanging(global::System.String value);
        partial void OnPozisyonAdıChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cinsiyet
        {
            get
            {
                return _Cinsiyet;
            }
            set
            {
                if (_Cinsiyet != value)
                {
                    OnCinsiyetChanging(value);
                    ReportPropertyChanging("Cinsiyet");
                    _Cinsiyet = StructuralObject.SetValidValue(value, false, "Cinsiyet");
                    ReportPropertyChanged("Cinsiyet");
                    OnCinsiyetChanged();
                }
            }
        }
        private global::System.String _Cinsiyet;
        partial void OnCinsiyetChanging(global::System.String value);
        partial void OnCinsiyetChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DereceKodu
        {
            get
            {
                return _DereceKodu;
            }
            set
            {
                OnDereceKoduChanging(value);
                ReportPropertyChanging("DereceKodu");
                _DereceKodu = StructuralObject.SetValidValue(value, true, "DereceKodu");
                ReportPropertyChanged("DereceKodu");
                OnDereceKoduChanged();
            }
        }
        private global::System.String _DereceKodu;
        partial void OnDereceKoduChanging(global::System.String value);
        partial void OnDereceKoduChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DereceAdi
        {
            get
            {
                return _DereceAdi;
            }
            set
            {
                OnDereceAdiChanging(value);
                ReportPropertyChanging("DereceAdi");
                _DereceAdi = StructuralObject.SetValidValue(value, true, "DereceAdi");
                ReportPropertyChanged("DereceAdi");
                OnDereceAdiChanged();
            }
        }
        private global::System.String _DereceAdi;
        partial void OnDereceAdiChanging(global::System.String value);
        partial void OnDereceAdiChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BordroKodu
        {
            get
            {
                return _BordroKodu;
            }
            set
            {
                OnBordroKoduChanging(value);
                ReportPropertyChanging("BordroKodu");
                _BordroKodu = StructuralObject.SetValidValue(value, true, "BordroKodu");
                ReportPropertyChanged("BordroKodu");
                OnBordroKoduChanged();
            }
        }
        private global::System.String _BordroKodu;
        partial void OnBordroKoduChanging(global::System.String value);
        partial void OnBordroKoduChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IseGirisTarihi
        {
            get
            {
                return _IseGirisTarihi;
            }
            set
            {
                OnIseGirisTarihiChanging(value);
                ReportPropertyChanging("IseGirisTarihi");
                _IseGirisTarihi = StructuralObject.SetValidValue(value, true, "IseGirisTarihi");
                ReportPropertyChanged("IseGirisTarihi");
                OnIseGirisTarihiChanged();
            }
        }
        private global::System.String _IseGirisTarihi;
        partial void OnIseGirisTarihiChanging(global::System.String value);
        partial void OnIseGirisTarihiChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IstenCikisTarihi
        {
            get
            {
                return _IstenCikisTarihi;
            }
            set
            {
                OnIstenCikisTarihiChanging(value);
                ReportPropertyChanging("IstenCikisTarihi");
                _IstenCikisTarihi = StructuralObject.SetValidValue(value, true, "IstenCikisTarihi");
                ReportPropertyChanged("IstenCikisTarihi");
                OnIstenCikisTarihiChanged();
            }
        }
        private global::System.String _IstenCikisTarihi;
        partial void OnIstenCikisTarihiChanging(global::System.String value);
        partial void OnIstenCikisTarihiChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> KidemYil
        {
            get
            {
                return _KidemYil;
            }
            set
            {
                OnKidemYilChanging(value);
                ReportPropertyChanging("KidemYil");
                _KidemYil = StructuralObject.SetValidValue(value, "KidemYil");
                ReportPropertyChanged("KidemYil");
                OnKidemYilChanged();
            }
        }
        private Nullable<global::System.Int32> _KidemYil;
        partial void OnKidemYilChanging(Nullable<global::System.Int32> value);
        partial void OnKidemYilChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BirincilYoneticiSicilNo
        {
            get
            {
                return _BirincilYoneticiSicilNo;
            }
            set
            {
                OnBirincilYoneticiSicilNoChanging(value);
                ReportPropertyChanging("BirincilYoneticiSicilNo");
                _BirincilYoneticiSicilNo = StructuralObject.SetValidValue(value, true, "BirincilYoneticiSicilNo");
                ReportPropertyChanged("BirincilYoneticiSicilNo");
                OnBirincilYoneticiSicilNoChanged();
            }
        }
        private global::System.String _BirincilYoneticiSicilNo;
        partial void OnBirincilYoneticiSicilNoChanging(global::System.String value);
        partial void OnBirincilYoneticiSicilNoChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BirincilYoneticiAd
        {
            get
            {
                return _BirincilYoneticiAd;
            }
            set
            {
                OnBirincilYoneticiAdChanging(value);
                ReportPropertyChanging("BirincilYoneticiAd");
                _BirincilYoneticiAd = StructuralObject.SetValidValue(value, true, "BirincilYoneticiAd");
                ReportPropertyChanged("BirincilYoneticiAd");
                OnBirincilYoneticiAdChanged();
            }
        }
        private global::System.String _BirincilYoneticiAd;
        partial void OnBirincilYoneticiAdChanging(global::System.String value);
        partial void OnBirincilYoneticiAdChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BirincilYoneticiSoyad
        {
            get
            {
                return _BirincilYoneticiSoyad;
            }
            set
            {
                OnBirincilYoneticiSoyadChanging(value);
                ReportPropertyChanging("BirincilYoneticiSoyad");
                _BirincilYoneticiSoyad = StructuralObject.SetValidValue(value, true, "BirincilYoneticiSoyad");
                ReportPropertyChanged("BirincilYoneticiSoyad");
                OnBirincilYoneticiSoyadChanged();
            }
        }
        private global::System.String _BirincilYoneticiSoyad;
        partial void OnBirincilYoneticiSoyadChanging(global::System.String value);
        partial void OnBirincilYoneticiSoyadChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BirincilYoneticiUnvanKodu
        {
            get
            {
                return _BirincilYoneticiUnvanKodu;
            }
            set
            {
                OnBirincilYoneticiUnvanKoduChanging(value);
                ReportPropertyChanging("BirincilYoneticiUnvanKodu");
                _BirincilYoneticiUnvanKodu = StructuralObject.SetValidValue(value, true, "BirincilYoneticiUnvanKodu");
                ReportPropertyChanged("BirincilYoneticiUnvanKodu");
                OnBirincilYoneticiUnvanKoduChanged();
            }
        }
        private global::System.String _BirincilYoneticiUnvanKodu;
        partial void OnBirincilYoneticiUnvanKoduChanging(global::System.String value);
        partial void OnBirincilYoneticiUnvanKoduChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IkincilYoneticiSicilNo
        {
            get
            {
                return _IkincilYoneticiSicilNo;
            }
            set
            {
                OnIkincilYoneticiSicilNoChanging(value);
                ReportPropertyChanging("IkincilYoneticiSicilNo");
                _IkincilYoneticiSicilNo = StructuralObject.SetValidValue(value, true, "IkincilYoneticiSicilNo");
                ReportPropertyChanged("IkincilYoneticiSicilNo");
                OnIkincilYoneticiSicilNoChanged();
            }
        }
        private global::System.String _IkincilYoneticiSicilNo;
        partial void OnIkincilYoneticiSicilNoChanging(global::System.String value);
        partial void OnIkincilYoneticiSicilNoChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IkincilYoneticiAd
        {
            get
            {
                return _IkincilYoneticiAd;
            }
            set
            {
                OnIkincilYoneticiAdChanging(value);
                ReportPropertyChanging("IkincilYoneticiAd");
                _IkincilYoneticiAd = StructuralObject.SetValidValue(value, true, "IkincilYoneticiAd");
                ReportPropertyChanged("IkincilYoneticiAd");
                OnIkincilYoneticiAdChanged();
            }
        }
        private global::System.String _IkincilYoneticiAd;
        partial void OnIkincilYoneticiAdChanging(global::System.String value);
        partial void OnIkincilYoneticiAdChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IkincilYoneticiSoyad
        {
            get
            {
                return _IkincilYoneticiSoyad;
            }
            set
            {
                OnIkincilYoneticiSoyadChanging(value);
                ReportPropertyChanging("IkincilYoneticiSoyad");
                _IkincilYoneticiSoyad = StructuralObject.SetValidValue(value, true, "IkincilYoneticiSoyad");
                ReportPropertyChanged("IkincilYoneticiSoyad");
                OnIkincilYoneticiSoyadChanged();
            }
        }
        private global::System.String _IkincilYoneticiSoyad;
        partial void OnIkincilYoneticiSoyadChanging(global::System.String value);
        partial void OnIkincilYoneticiSoyadChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IkincilYoneticiUnvanKodu
        {
            get
            {
                return _IkincilYoneticiUnvanKodu;
            }
            set
            {
                OnIkincilYoneticiUnvanKoduChanging(value);
                ReportPropertyChanging("IkincilYoneticiUnvanKodu");
                _IkincilYoneticiUnvanKodu = StructuralObject.SetValidValue(value, true, "IkincilYoneticiUnvanKodu");
                ReportPropertyChanged("IkincilYoneticiUnvanKodu");
                OnIkincilYoneticiUnvanKoduChanged();
            }
        }
        private global::System.String _IkincilYoneticiUnvanKodu;
        partial void OnIkincilYoneticiUnvanKoduChanging(global::System.String value);
        partial void OnIkincilYoneticiUnvanKoduChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DOĞUM_TARİHİ
        {
            get
            {
                return _DOĞUM_TARİHİ;
            }
            set
            {
                if (_DOĞUM_TARİHİ != value)
                {
                    OnDOĞUM_TARİHİChanging(value);
                    ReportPropertyChanging("DOĞUM_TARİHİ");
                    _DOĞUM_TARİHİ = StructuralObject.SetValidValue(value, "DOĞUM_TARİHİ");
                    ReportPropertyChanged("DOĞUM_TARİHİ");
                    OnDOĞUM_TARİHİChanged();
                }
            }
        }
        private global::System.DateTime _DOĞUM_TARİHİ;
        partial void OnDOĞUM_TARİHİChanging(global::System.DateTime value);
        partial void OnDOĞUM_TARİHİChanged();

        #endregion

    }

    #endregion

}
